// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: package.proto

#ifndef PROTOBUF_package_2eproto__INCLUDED
#define PROTOBUF_package_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include "common.pb.h"  // IWYU pragma: export
// @@protoc_insertion_point(includes)

namespace protbuf {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_package_2eproto();
void protobuf_AssignDesc_package_2eproto();
void protobuf_ShutdownFile_package_2eproto();

class Package;

// ===================================================================

class Package : public ::google::protobuf::MessageLite {
 public:
  Package();
  virtual ~Package();

  Package(const Package& from);

  inline Package& operator=(const Package& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::std::string* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const Package& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const Package* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(Package* other);

  // implements Message ----------------------------------------------

  Package* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const Package& from);
  void MergeFrom(const Package& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::uint32 id() const;
  inline void set_id(::google::protobuf::uint32 value);

  // optional string name = 2;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 2;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // optional string description = 3;
  inline bool has_description() const;
  inline void clear_description();
  static const int kDescriptionFieldNumber = 3;
  inline const ::std::string& description() const;
  inline void set_description(const ::std::string& value);
  inline void set_description(const char* value);
  inline void set_description(const char* value, size_t size);
  inline ::std::string* mutable_description();
  inline ::std::string* release_description();
  inline void set_allocated_description(::std::string* description);

  // optional fixed64 creationDate = 4;
  inline bool has_creationdate() const;
  inline void clear_creationdate();
  static const int kCreationDateFieldNumber = 4;
  inline ::google::protobuf::uint64 creationdate() const;
  inline void set_creationdate(::google::protobuf::uint64 value);

  // optional fixed64 lastupdate = 5;
  inline bool has_lastupdate() const;
  inline void clear_lastupdate();
  static const int kLastupdateFieldNumber = 5;
  inline ::google::protobuf::uint64 lastupdate() const;
  inline void set_lastupdate(::google::protobuf::uint64 value);

  // optional string mount_type = 6;
  inline bool has_mount_type() const;
  inline void clear_mount_type();
  static const int kMountTypeFieldNumber = 6;
  inline const ::std::string& mount_type() const;
  inline void set_mount_type(const ::std::string& value);
  inline void set_mount_type(const char* value);
  inline void set_mount_type(const char* value, size_t size);
  inline ::std::string* mutable_mount_type();
  inline ::std::string* release_mount_type();
  inline void set_allocated_mount_type(::std::string* mount_type);

  // optional uint32 pin_number = 7;
  inline bool has_pin_number() const;
  inline void clear_pin_number();
  static const int kPinNumberFieldNumber = 7;
  inline ::google::protobuf::uint32 pin_number() const;
  inline void set_pin_number(::google::protobuf::uint32 value);

  // optional bytes config = 8;
  inline bool has_config() const;
  inline void clear_config();
  static const int kConfigFieldNumber = 8;
  inline const ::std::string& config() const;
  inline void set_config(const ::std::string& value);
  inline void set_config(const char* value);
  inline void set_config(const void* value, size_t size);
  inline ::std::string* mutable_config();
  inline ::std::string* release_config();
  inline void set_allocated_config(::std::string* config);

  // @@protoc_insertion_point(class_scope:protbuf.Package)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_description();
  inline void clear_has_description();
  inline void set_has_creationdate();
  inline void clear_has_creationdate();
  inline void set_has_lastupdate();
  inline void clear_has_lastupdate();
  inline void set_has_mount_type();
  inline void clear_has_mount_type();
  inline void set_has_pin_number();
  inline void clear_has_pin_number();
  inline void set_has_config();
  inline void clear_has_config();

  ::std::string _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* name_;
  ::std::string* description_;
  ::google::protobuf::uint64 creationdate_;
  ::google::protobuf::uint32 id_;
  ::google::protobuf::uint32 pin_number_;
  ::google::protobuf::uint64 lastupdate_;
  ::std::string* mount_type_;
  ::std::string* config_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_package_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_package_2eproto();
  #endif
  friend void protobuf_AssignDesc_package_2eproto();
  friend void protobuf_ShutdownFile_package_2eproto();

  void InitAsDefaultInstance();
  static Package* default_instance_;
};
// ===================================================================


// ===================================================================

// Package

// required uint32 id = 1;
inline bool Package::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Package::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Package::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Package::clear_id() {
  id_ = 0u;
  clear_has_id();
}
inline ::google::protobuf::uint32 Package::id() const {
  // @@protoc_insertion_point(field_get:protbuf.Package.id)
  return id_;
}
inline void Package::set_id(::google::protobuf::uint32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:protbuf.Package.id)
}

// optional string name = 2;
inline bool Package::has_name() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Package::set_has_name() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Package::clear_has_name() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Package::clear_name() {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& Package::name() const {
  // @@protoc_insertion_point(field_get:protbuf.Package.name)
  return *name_;
}
inline void Package::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set:protbuf.Package.name)
}
inline void Package::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(value);
  // @@protoc_insertion_point(field_set_char:protbuf.Package.name)
}
inline void Package::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:protbuf.Package.name)
}
inline ::std::string* Package::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    name_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:protbuf.Package.name)
  return name_;
}
inline ::std::string* Package::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Package::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:protbuf.Package.name)
}

// optional string description = 3;
inline bool Package::has_description() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Package::set_has_description() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Package::clear_has_description() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Package::clear_description() {
  if (description_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    description_->clear();
  }
  clear_has_description();
}
inline const ::std::string& Package::description() const {
  // @@protoc_insertion_point(field_get:protbuf.Package.description)
  return *description_;
}
inline void Package::set_description(const ::std::string& value) {
  set_has_description();
  if (description_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    description_ = new ::std::string;
  }
  description_->assign(value);
  // @@protoc_insertion_point(field_set:protbuf.Package.description)
}
inline void Package::set_description(const char* value) {
  set_has_description();
  if (description_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    description_ = new ::std::string;
  }
  description_->assign(value);
  // @@protoc_insertion_point(field_set_char:protbuf.Package.description)
}
inline void Package::set_description(const char* value, size_t size) {
  set_has_description();
  if (description_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    description_ = new ::std::string;
  }
  description_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:protbuf.Package.description)
}
inline ::std::string* Package::mutable_description() {
  set_has_description();
  if (description_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    description_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:protbuf.Package.description)
  return description_;
}
inline ::std::string* Package::release_description() {
  clear_has_description();
  if (description_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = description_;
    description_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Package::set_allocated_description(::std::string* description) {
  if (description_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete description_;
  }
  if (description) {
    set_has_description();
    description_ = description;
  } else {
    clear_has_description();
    description_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:protbuf.Package.description)
}

// optional fixed64 creationDate = 4;
inline bool Package::has_creationdate() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Package::set_has_creationdate() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Package::clear_has_creationdate() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Package::clear_creationdate() {
  creationdate_ = GOOGLE_ULONGLONG(0);
  clear_has_creationdate();
}
inline ::google::protobuf::uint64 Package::creationdate() const {
  // @@protoc_insertion_point(field_get:protbuf.Package.creationDate)
  return creationdate_;
}
inline void Package::set_creationdate(::google::protobuf::uint64 value) {
  set_has_creationdate();
  creationdate_ = value;
  // @@protoc_insertion_point(field_set:protbuf.Package.creationDate)
}

// optional fixed64 lastupdate = 5;
inline bool Package::has_lastupdate() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Package::set_has_lastupdate() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Package::clear_has_lastupdate() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Package::clear_lastupdate() {
  lastupdate_ = GOOGLE_ULONGLONG(0);
  clear_has_lastupdate();
}
inline ::google::protobuf::uint64 Package::lastupdate() const {
  // @@protoc_insertion_point(field_get:protbuf.Package.lastupdate)
  return lastupdate_;
}
inline void Package::set_lastupdate(::google::protobuf::uint64 value) {
  set_has_lastupdate();
  lastupdate_ = value;
  // @@protoc_insertion_point(field_set:protbuf.Package.lastupdate)
}

// optional string mount_type = 6;
inline bool Package::has_mount_type() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Package::set_has_mount_type() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Package::clear_has_mount_type() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Package::clear_mount_type() {
  if (mount_type_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    mount_type_->clear();
  }
  clear_has_mount_type();
}
inline const ::std::string& Package::mount_type() const {
  // @@protoc_insertion_point(field_get:protbuf.Package.mount_type)
  return *mount_type_;
}
inline void Package::set_mount_type(const ::std::string& value) {
  set_has_mount_type();
  if (mount_type_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    mount_type_ = new ::std::string;
  }
  mount_type_->assign(value);
  // @@protoc_insertion_point(field_set:protbuf.Package.mount_type)
}
inline void Package::set_mount_type(const char* value) {
  set_has_mount_type();
  if (mount_type_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    mount_type_ = new ::std::string;
  }
  mount_type_->assign(value);
  // @@protoc_insertion_point(field_set_char:protbuf.Package.mount_type)
}
inline void Package::set_mount_type(const char* value, size_t size) {
  set_has_mount_type();
  if (mount_type_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    mount_type_ = new ::std::string;
  }
  mount_type_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:protbuf.Package.mount_type)
}
inline ::std::string* Package::mutable_mount_type() {
  set_has_mount_type();
  if (mount_type_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    mount_type_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:protbuf.Package.mount_type)
  return mount_type_;
}
inline ::std::string* Package::release_mount_type() {
  clear_has_mount_type();
  if (mount_type_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = mount_type_;
    mount_type_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Package::set_allocated_mount_type(::std::string* mount_type) {
  if (mount_type_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete mount_type_;
  }
  if (mount_type) {
    set_has_mount_type();
    mount_type_ = mount_type;
  } else {
    clear_has_mount_type();
    mount_type_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:protbuf.Package.mount_type)
}

// optional uint32 pin_number = 7;
inline bool Package::has_pin_number() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void Package::set_has_pin_number() {
  _has_bits_[0] |= 0x00000040u;
}
inline void Package::clear_has_pin_number() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void Package::clear_pin_number() {
  pin_number_ = 0u;
  clear_has_pin_number();
}
inline ::google::protobuf::uint32 Package::pin_number() const {
  // @@protoc_insertion_point(field_get:protbuf.Package.pin_number)
  return pin_number_;
}
inline void Package::set_pin_number(::google::protobuf::uint32 value) {
  set_has_pin_number();
  pin_number_ = value;
  // @@protoc_insertion_point(field_set:protbuf.Package.pin_number)
}

// optional bytes config = 8;
inline bool Package::has_config() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void Package::set_has_config() {
  _has_bits_[0] |= 0x00000080u;
}
inline void Package::clear_has_config() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void Package::clear_config() {
  if (config_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    config_->clear();
  }
  clear_has_config();
}
inline const ::std::string& Package::config() const {
  // @@protoc_insertion_point(field_get:protbuf.Package.config)
  return *config_;
}
inline void Package::set_config(const ::std::string& value) {
  set_has_config();
  if (config_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    config_ = new ::std::string;
  }
  config_->assign(value);
  // @@protoc_insertion_point(field_set:protbuf.Package.config)
}
inline void Package::set_config(const char* value) {
  set_has_config();
  if (config_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    config_ = new ::std::string;
  }
  config_->assign(value);
  // @@protoc_insertion_point(field_set_char:protbuf.Package.config)
}
inline void Package::set_config(const void* value, size_t size) {
  set_has_config();
  if (config_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    config_ = new ::std::string;
  }
  config_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:protbuf.Package.config)
}
inline ::std::string* Package::mutable_config() {
  set_has_config();
  if (config_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    config_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:protbuf.Package.config)
  return config_;
}
inline ::std::string* Package::release_config() {
  clear_has_config();
  if (config_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = config_;
    config_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Package::set_allocated_config(::std::string* config) {
  if (config_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete config_;
  }
  if (config) {
    set_has_config();
    config_ = config;
  } else {
    clear_has_config();
    config_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:protbuf.Package.config)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protbuf

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_package_2eproto__INCLUDED
