# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: item.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import user_pb2
import group_pb2
import package_pb2
import parameters_pb2
import common_pb2

from user_pb2 import *
from group_pb2 import *
from package_pb2 import *
from parameters_pb2 import *
from common_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='item.proto',
  package='protbuf',
  serialized_pb=_b('\n\nitem.proto\x12\x07protbuf\x1a\nuser.proto\x1a\x0bgroup.proto\x1a\rpackage.proto\x1a\x10parameters.proto\x1a\x0c\x63ommon.proto\"+\n\x0eItemParameters\x12\n\n\x02id\x18\x01 \x02(\r\x12\r\n\x05value\x18\x02 \x02(\x0c\"9\n\rItemBasicInfo\x12\n\n\x02id\x18\x01 \x02(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06symbol\x18\x03 \x01(\t\"\xb0\x01\n\x0bItemDetails\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x12\n\nname_space\x18\x05 \x02(\t\x12\x14\n\x0cprivate_item\x18\x06 \x02(\x08\x12\x12\n\npackage_id\x18\x08 \x01(\r\x12\x0f\n\x07user_id\x18\t \x01(\r\x12\x10\n\x08group_id\x18\n \x01(\r\x12+\n\nparameters\x18\x07 \x03(\x0b\x32\x17.protbuf.ItemParameters\"\\\n\x0cItemFullData\x12%\n\x05\x62\x61sic\x18\x01 \x02(\x0b\x32\x16.protbuf.ItemBasicInfo\x12%\n\x07\x64\x65tails\x18\x02 \x02(\x0b\x32\x14.protbuf.ItemDetailsB\x02H\x03P\x00P\x01P\x02P\x03P\x04')
  ,
  dependencies=[user_pb2.DESCRIPTOR,group_pb2.DESCRIPTOR,package_pb2.DESCRIPTOR,parameters_pb2.DESCRIPTOR,common_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ITEMPARAMETERS = _descriptor.Descriptor(
  name='ItemParameters',
  full_name='protbuf.ItemParameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='protbuf.ItemParameters.id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='protbuf.ItemParameters.value', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=138,
)


_ITEMBASICINFO = _descriptor.Descriptor(
  name='ItemBasicInfo',
  full_name='protbuf.ItemBasicInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='protbuf.ItemBasicInfo.id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='protbuf.ItemBasicInfo.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='symbol', full_name='protbuf.ItemBasicInfo.symbol', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=197,
)


_ITEMDETAILS = _descriptor.Descriptor(
  name='ItemDetails',
  full_name='protbuf.ItemDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='description', full_name='protbuf.ItemDetails.description', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name_space', full_name='protbuf.ItemDetails.name_space', index=1,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='private_item', full_name='protbuf.ItemDetails.private_item', index=2,
      number=6, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='package_id', full_name='protbuf.ItemDetails.package_id', index=3,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='protbuf.ItemDetails.user_id', index=4,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='group_id', full_name='protbuf.ItemDetails.group_id', index=5,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='parameters', full_name='protbuf.ItemDetails.parameters', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=200,
  serialized_end=376,
)


_ITEMFULLDATA = _descriptor.Descriptor(
  name='ItemFullData',
  full_name='protbuf.ItemFullData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='basic', full_name='protbuf.ItemFullData.basic', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='details', full_name='protbuf.ItemFullData.details', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=378,
  serialized_end=470,
)

_ITEMDETAILS.fields_by_name['parameters'].message_type = _ITEMPARAMETERS
_ITEMFULLDATA.fields_by_name['basic'].message_type = _ITEMBASICINFO
_ITEMFULLDATA.fields_by_name['details'].message_type = _ITEMDETAILS
DESCRIPTOR.message_types_by_name['ItemParameters'] = _ITEMPARAMETERS
DESCRIPTOR.message_types_by_name['ItemBasicInfo'] = _ITEMBASICINFO
DESCRIPTOR.message_types_by_name['ItemDetails'] = _ITEMDETAILS
DESCRIPTOR.message_types_by_name['ItemFullData'] = _ITEMFULLDATA

ItemParameters = _reflection.GeneratedProtocolMessageType('ItemParameters', (_message.Message,), dict(
  DESCRIPTOR = _ITEMPARAMETERS,
  __module__ = 'item_pb2'
  # @@protoc_insertion_point(class_scope:protbuf.ItemParameters)
  ))
_sym_db.RegisterMessage(ItemParameters)

ItemBasicInfo = _reflection.GeneratedProtocolMessageType('ItemBasicInfo', (_message.Message,), dict(
  DESCRIPTOR = _ITEMBASICINFO,
  __module__ = 'item_pb2'
  # @@protoc_insertion_point(class_scope:protbuf.ItemBasicInfo)
  ))
_sym_db.RegisterMessage(ItemBasicInfo)

ItemDetails = _reflection.GeneratedProtocolMessageType('ItemDetails', (_message.Message,), dict(
  DESCRIPTOR = _ITEMDETAILS,
  __module__ = 'item_pb2'
  # @@protoc_insertion_point(class_scope:protbuf.ItemDetails)
  ))
_sym_db.RegisterMessage(ItemDetails)

ItemFullData = _reflection.GeneratedProtocolMessageType('ItemFullData', (_message.Message,), dict(
  DESCRIPTOR = _ITEMFULLDATA,
  __module__ = 'item_pb2'
  # @@protoc_insertion_point(class_scope:protbuf.ItemFullData)
  ))
_sym_db.RegisterMessage(ItemFullData)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\003'))
# @@protoc_insertion_point(module_scope)
