# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_conteiner.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2
import user_pb2

from common_pb2 import *
from user_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='message_conteiner.proto',
  package='protbuf',
  serialized_pb=_b('\n\x17message_conteiner.proto\x12\x07protbuf\x1a\x0c\x63ommon.proto\x1a\nuser.proto\"9\n\x0e\x43lientRequests\x12\'\n\x07request\x18\x01 \x03(\x0b\x32\x16.protbuf.ClientRequest\"Y\n\rClientRequest\x12\x14\n\trequestId\x18\x01 \x01(\r:\x01\x31\x12*\n\nmsgUserReq\x18\x0c \x01(\x0b\x32\x14.user.MsgUserRequestH\x00\x42\x06\n\x04\x64\x61ta\"<\n\x0fServerResponses\x12)\n\x08response\x18\x01 \x03(\x0b\x32\x17.protbuf.ServerResponse\"\xb1\x01\n\x0eServerResponse\x12\x1c\n\x05\x63odes\x18\x01 \x03(\x0b\x32\r.ResponseCode\x12\x15\n\nresponseId\x18\x02 \x01(\r:\x01\x30\x12+\n\nmsgUserRes\x18\r \x01(\x0b\x32\x15.user.MsgUserResponseH\x00\x12\x35\n\x11msgServerResponse\x18\xe8\x07 \x01(\x0b\x32\x17.protbuf.ServerResponseH\x00\x42\x06\n\x04\x64\x61ta*4\n\tMsgCoding\x12\x0e\n\nmsgProtbuf\x10\x01\x12\n\n\x06msgBin\x10\x02\x12\x0b\n\x07msgJson\x10\x03*Y\n\tMsgTypeId\x12\x0f\n\x0bMsg_unknown\x10\x00\x12\x17\n\x13Msg_Server_Response\x10\x64\x12\x10\n\x0cMsg_User_req\x10\x0c\x12\x10\n\x0cMsg_User_res\x10\r*(\n\x10ServerErrorCodes\x12\x14\n\x10\x45rror_MsgUnknown\x10\x01\x42\x02H\x03P\x00P\x01')
  ,
  dependencies=[common_pb2.DESCRIPTOR,user_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_MSGCODING = _descriptor.EnumDescriptor(
  name='MsgCoding',
  full_name='protbuf.MsgCoding',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='msgProtbuf', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='msgBin', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='msgJson', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=454,
  serialized_end=506,
)
_sym_db.RegisterEnumDescriptor(_MSGCODING)

MsgCoding = enum_type_wrapper.EnumTypeWrapper(_MSGCODING)
_MSGTYPEID = _descriptor.EnumDescriptor(
  name='MsgTypeId',
  full_name='protbuf.MsgTypeId',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Msg_unknown', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Msg_Server_Response', index=1, number=100,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Msg_User_req', index=2, number=12,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Msg_User_res', index=3, number=13,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=508,
  serialized_end=597,
)
_sym_db.RegisterEnumDescriptor(_MSGTYPEID)

MsgTypeId = enum_type_wrapper.EnumTypeWrapper(_MSGTYPEID)
_SERVERERRORCODES = _descriptor.EnumDescriptor(
  name='ServerErrorCodes',
  full_name='protbuf.ServerErrorCodes',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Error_MsgUnknown', index=0, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=599,
  serialized_end=639,
)
_sym_db.RegisterEnumDescriptor(_SERVERERRORCODES)

ServerErrorCodes = enum_type_wrapper.EnumTypeWrapper(_SERVERERRORCODES)
msgProtbuf = 1
msgBin = 2
msgJson = 3
Msg_unknown = 0
Msg_Server_Response = 100
Msg_User_req = 12
Msg_User_res = 13
Error_MsgUnknown = 1



_CLIENTREQUESTS = _descriptor.Descriptor(
  name='ClientRequests',
  full_name='protbuf.ClientRequests',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request', full_name='protbuf.ClientRequests.request', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=119,
)


_CLIENTREQUEST = _descriptor.Descriptor(
  name='ClientRequest',
  full_name='protbuf.ClientRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='requestId', full_name='protbuf.ClientRequest.requestId', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='msgUserReq', full_name='protbuf.ClientRequest.msgUserReq', index=1,
      number=12, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='data', full_name='protbuf.ClientRequest.data',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=121,
  serialized_end=210,
)


_SERVERRESPONSES = _descriptor.Descriptor(
  name='ServerResponses',
  full_name='protbuf.ServerResponses',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='protbuf.ServerResponses.response', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=212,
  serialized_end=272,
)


_SERVERRESPONSE = _descriptor.Descriptor(
  name='ServerResponse',
  full_name='protbuf.ServerResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='codes', full_name='protbuf.ServerResponse.codes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='responseId', full_name='protbuf.ServerResponse.responseId', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='msgUserRes', full_name='protbuf.ServerResponse.msgUserRes', index=2,
      number=13, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='msgServerResponse', full_name='protbuf.ServerResponse.msgServerResponse', index=3,
      number=1000, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='data', full_name='protbuf.ServerResponse.data',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=275,
  serialized_end=452,
)

_CLIENTREQUESTS.fields_by_name['request'].message_type = _CLIENTREQUEST
_CLIENTREQUEST.fields_by_name['msgUserReq'].message_type = user_pb2._MSGUSERREQUEST
_CLIENTREQUEST.oneofs_by_name['data'].fields.append(
  _CLIENTREQUEST.fields_by_name['msgUserReq'])
_CLIENTREQUEST.fields_by_name['msgUserReq'].containing_oneof = _CLIENTREQUEST.oneofs_by_name['data']
_SERVERRESPONSES.fields_by_name['response'].message_type = _SERVERRESPONSE
_SERVERRESPONSE.fields_by_name['codes'].message_type = common_pb2._RESPONSECODE
_SERVERRESPONSE.fields_by_name['msgUserRes'].message_type = user_pb2._MSGUSERRESPONSE
_SERVERRESPONSE.fields_by_name['msgServerResponse'].message_type = _SERVERRESPONSE
_SERVERRESPONSE.oneofs_by_name['data'].fields.append(
  _SERVERRESPONSE.fields_by_name['msgUserRes'])
_SERVERRESPONSE.fields_by_name['msgUserRes'].containing_oneof = _SERVERRESPONSE.oneofs_by_name['data']
_SERVERRESPONSE.oneofs_by_name['data'].fields.append(
  _SERVERRESPONSE.fields_by_name['msgServerResponse'])
_SERVERRESPONSE.fields_by_name['msgServerResponse'].containing_oneof = _SERVERRESPONSE.oneofs_by_name['data']
DESCRIPTOR.message_types_by_name['ClientRequests'] = _CLIENTREQUESTS
DESCRIPTOR.message_types_by_name['ClientRequest'] = _CLIENTREQUEST
DESCRIPTOR.message_types_by_name['ServerResponses'] = _SERVERRESPONSES
DESCRIPTOR.message_types_by_name['ServerResponse'] = _SERVERRESPONSE
DESCRIPTOR.enum_types_by_name['MsgCoding'] = _MSGCODING
DESCRIPTOR.enum_types_by_name['MsgTypeId'] = _MSGTYPEID
DESCRIPTOR.enum_types_by_name['ServerErrorCodes'] = _SERVERERRORCODES

ClientRequests = _reflection.GeneratedProtocolMessageType('ClientRequests', (_message.Message,), dict(
  DESCRIPTOR = _CLIENTREQUESTS,
  __module__ = 'message_conteiner_pb2'
  # @@protoc_insertion_point(class_scope:protbuf.ClientRequests)
  ))
_sym_db.RegisterMessage(ClientRequests)

ClientRequest = _reflection.GeneratedProtocolMessageType('ClientRequest', (_message.Message,), dict(
  DESCRIPTOR = _CLIENTREQUEST,
  __module__ = 'message_conteiner_pb2'
  # @@protoc_insertion_point(class_scope:protbuf.ClientRequest)
  ))
_sym_db.RegisterMessage(ClientRequest)

ServerResponses = _reflection.GeneratedProtocolMessageType('ServerResponses', (_message.Message,), dict(
  DESCRIPTOR = _SERVERRESPONSES,
  __module__ = 'message_conteiner_pb2'
  # @@protoc_insertion_point(class_scope:protbuf.ServerResponses)
  ))
_sym_db.RegisterMessage(ServerResponses)

ServerResponse = _reflection.GeneratedProtocolMessageType('ServerResponse', (_message.Message,), dict(
  DESCRIPTOR = _SERVERRESPONSE,
  __module__ = 'message_conteiner_pb2'
  # @@protoc_insertion_point(class_scope:protbuf.ServerResponse)
  ))
_sym_db.RegisterMessage(ServerResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\003'))
# @@protoc_insertion_point(module_scope)
