# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: parameters.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2

from common_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='parameters.proto',
  package='protbuf',
  serialized_pb=_b('\n\x10parameters.proto\x12\x07protbuf\x1a\x0c\x63ommon.proto\"V\n\x07\x44\x65tails\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x14\n\x0c\x63reationDate\x18\x03 \x01(\x06\x12\x12\n\nlastupdate\x18\x04 \x01(\x06\"\x7f\n\x0fParameterConfig\x12\x0c\n\x04type\x18\x01 \x02(\x05\x12\x14\n\x0c\x64\x65\x66\x61ultValue\x18\x02 \x01(\x0c\x12\x10\n\x08minValue\x18\x03 \x01(\x0c\x12\x10\n\x08maxValue\x18\x04 \x01(\x0c\x12\x11\n\tminLength\x18\x05 \x01(\x05\x12\x11\n\tmaxLength\x18\x06 \x01(\x05\"\'\n\x10ParameterDetails\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\">\n\x12ParameterBasicInfo\x12\n\n\x02id\x18\x01 \x02(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06symbol\x18\x03 \x01(\t\"\x84\x01\n\tParameter\x12*\n\x05\x62\x61sic\x18\x01 \x02(\x0b\x32\x1b.protbuf.ParameterBasicInfo\x12!\n\x07\x64\x65tails\x18\x02 \x02(\x0b\x32\x10.protbuf.Details\x12(\n\x06\x63onfig\x18\x04 \x02(\x0b\x32\x18.protbuf.ParameterConfigB\x02H\x03P\x00')
  ,
  dependencies=[common_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DETAILS = _descriptor.Descriptor(
  name='Details',
  full_name='protbuf.Details',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='protbuf.Details.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='protbuf.Details.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='creationDate', full_name='protbuf.Details.creationDate', index=2,
      number=3, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lastupdate', full_name='protbuf.Details.lastupdate', index=3,
      number=4, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=129,
)


_PARAMETERCONFIG = _descriptor.Descriptor(
  name='ParameterConfig',
  full_name='protbuf.ParameterConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='protbuf.ParameterConfig.type', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='defaultValue', full_name='protbuf.ParameterConfig.defaultValue', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='minValue', full_name='protbuf.ParameterConfig.minValue', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='maxValue', full_name='protbuf.ParameterConfig.maxValue', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='minLength', full_name='protbuf.ParameterConfig.minLength', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='maxLength', full_name='protbuf.ParameterConfig.maxLength', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=258,
)


_PARAMETERDETAILS = _descriptor.Descriptor(
  name='ParameterDetails',
  full_name='protbuf.ParameterDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='description', full_name='protbuf.ParameterDetails.description', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=260,
  serialized_end=299,
)


_PARAMETERBASICINFO = _descriptor.Descriptor(
  name='ParameterBasicInfo',
  full_name='protbuf.ParameterBasicInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='protbuf.ParameterBasicInfo.id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='protbuf.ParameterBasicInfo.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='symbol', full_name='protbuf.ParameterBasicInfo.symbol', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=301,
  serialized_end=363,
)


_PARAMETER = _descriptor.Descriptor(
  name='Parameter',
  full_name='protbuf.Parameter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='basic', full_name='protbuf.Parameter.basic', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='details', full_name='protbuf.Parameter.details', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='config', full_name='protbuf.Parameter.config', index=2,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=366,
  serialized_end=498,
)

_PARAMETER.fields_by_name['basic'].message_type = _PARAMETERBASICINFO
_PARAMETER.fields_by_name['details'].message_type = _DETAILS
_PARAMETER.fields_by_name['config'].message_type = _PARAMETERCONFIG
DESCRIPTOR.message_types_by_name['Details'] = _DETAILS
DESCRIPTOR.message_types_by_name['ParameterConfig'] = _PARAMETERCONFIG
DESCRIPTOR.message_types_by_name['ParameterDetails'] = _PARAMETERDETAILS
DESCRIPTOR.message_types_by_name['ParameterBasicInfo'] = _PARAMETERBASICINFO
DESCRIPTOR.message_types_by_name['Parameter'] = _PARAMETER

Details = _reflection.GeneratedProtocolMessageType('Details', (_message.Message,), dict(
  DESCRIPTOR = _DETAILS,
  __module__ = 'parameters_pb2'
  # @@protoc_insertion_point(class_scope:protbuf.Details)
  ))
_sym_db.RegisterMessage(Details)

ParameterConfig = _reflection.GeneratedProtocolMessageType('ParameterConfig', (_message.Message,), dict(
  DESCRIPTOR = _PARAMETERCONFIG,
  __module__ = 'parameters_pb2'
  # @@protoc_insertion_point(class_scope:protbuf.ParameterConfig)
  ))
_sym_db.RegisterMessage(ParameterConfig)

ParameterDetails = _reflection.GeneratedProtocolMessageType('ParameterDetails', (_message.Message,), dict(
  DESCRIPTOR = _PARAMETERDETAILS,
  __module__ = 'parameters_pb2'
  # @@protoc_insertion_point(class_scope:protbuf.ParameterDetails)
  ))
_sym_db.RegisterMessage(ParameterDetails)

ParameterBasicInfo = _reflection.GeneratedProtocolMessageType('ParameterBasicInfo', (_message.Message,), dict(
  DESCRIPTOR = _PARAMETERBASICINFO,
  __module__ = 'parameters_pb2'
  # @@protoc_insertion_point(class_scope:protbuf.ParameterBasicInfo)
  ))
_sym_db.RegisterMessage(ParameterBasicInfo)

Parameter = _reflection.GeneratedProtocolMessageType('Parameter', (_message.Message,), dict(
  DESCRIPTOR = _PARAMETER,
  __module__ = 'parameters_pb2'
  # @@protoc_insertion_point(class_scope:protbuf.Parameter)
  ))
_sym_db.RegisterMessage(Parameter)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\003'))
# @@protoc_insertion_point(module_scope)
