# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: storage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2

from common_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='storage.proto',
  package='protbuf',
  serialized_pb=_b('\n\rstorage.proto\x12\x07protbuf\x1a\x0c\x63ommon.proto\"\x13\n\x11StorageStatistics\"t\n\x07Storage\x12\n\n\x02id\x18\x01 \x02(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x14\n\x0c\x63reationDate\x18\x04 \x01(\x06\x12\x12\n\nlastupdate\x18\x05 \x01(\x06\x12\x10\n\x08owner_id\x18\x06 \x01(\rB\x02H\x03P\x00')
  ,
  dependencies=[common_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_STORAGESTATISTICS = _descriptor.Descriptor(
  name='StorageStatistics',
  full_name='protbuf.StorageStatistics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=59,
)


_STORAGE = _descriptor.Descriptor(
  name='Storage',
  full_name='protbuf.Storage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='protbuf.Storage.id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='protbuf.Storage.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='protbuf.Storage.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='creationDate', full_name='protbuf.Storage.creationDate', index=3,
      number=4, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lastupdate', full_name='protbuf.Storage.lastupdate', index=4,
      number=5, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='owner_id', full_name='protbuf.Storage.owner_id', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=177,
)

DESCRIPTOR.message_types_by_name['StorageStatistics'] = _STORAGESTATISTICS
DESCRIPTOR.message_types_by_name['Storage'] = _STORAGE

StorageStatistics = _reflection.GeneratedProtocolMessageType('StorageStatistics', (_message.Message,), dict(
  DESCRIPTOR = _STORAGESTATISTICS,
  __module__ = 'storage_pb2'
  # @@protoc_insertion_point(class_scope:protbuf.StorageStatistics)
  ))
_sym_db.RegisterMessage(StorageStatistics)

Storage = _reflection.GeneratedProtocolMessageType('Storage', (_message.Message,), dict(
  DESCRIPTOR = _STORAGE,
  __module__ = 'storage_pb2'
  # @@protoc_insertion_point(class_scope:protbuf.Storage)
  ))
_sym_db.RegisterMessage(Storage)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\003'))
# @@protoc_insertion_point(module_scope)
